In [1]:
#! ipython suppress id=a299071e366b4bd590198b85b8625f2b
%pushd book-materials
import numpy as np
import pandas as pd
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 25
pd.options.display.max_columns = 20
pd.options.display.max_colwidth = 82
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [26]:
#! ipython suppress id=835e9c4e6d3942638244064db595a5bd
import numpy as np
import pandas as pd

In [2]:
#! ipython id=290a88142afe4854bc724c7a6c735bae
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [3]:
#! ipython id=4b91ad05aea045cdbf13b5900cc1f73e
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
#! ipython id=8996ec87330f486b96f59f1f394ccf6a
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data


0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [5]:
string_data.isna()


0    False
1     True
2     True
3    False
dtype: bool

In [6]:
float_data = pd.Series([1, 2, None], dtype='float64')
float_data


0    1.0
1    2.0
2    NaN
dtype: float64

In [7]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [8]:
from numpy import nan as NA

In [9]:
#! ipython id=6dfb795c00c24da9a66cdd66870f9fa9
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
#! ipython id=ce4c091e5f824312b06c6b1d6ff531fb
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
#! ipython id=be32168b85724034b62a96f6fb6e7f2c
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data


0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
limpeza=data.dropna()
limpeza

0    1    2
0  1.0  6.5  3.0

In [13]:
#! ipython id=fc78d6354b4541f3a1c2416275e68c76
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [14]:
#! ipython id=87ba756b91eb4dd09d1b7e647a8ae7b9
data[4] = np.nan
data


0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [15]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
#! ipython id=93bc1cf6fc10429a924cea596353e388
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df


0         1         2
0  0.238404       NaN       NaN
1 -1.044114       NaN       NaN
2  0.642804       NaN -1.628695
3  0.501038       NaN  1.832153
4  2.847076 -0.176141 -0.543126
5 -0.018326 -0.100503 -1.181996
6  0.131721  0.314774  2.846230

In [17]:
df.dropna()


0         1         2
4  2.847076 -0.176141 -0.543126
5 -0.018326 -0.100503 -1.181996
6  0.131721  0.314774  2.846230

In [21]:
df.dropna(thresh=2)

0         1         2
2  0.642804       NaN -1.628695
3  0.501038       NaN  1.832153
4  2.847076 -0.176141 -0.543126
5 -0.018326 -0.100503 -1.181996
6  0.131721  0.314774  2.846230

In [22]:
#! ipython id=ceee3ece49cc4169a1f8ac1e6954accd
df.fillna(0)

0         1         2
0  0.238404  0.000000  0.000000
1 -1.044114  0.000000  0.000000
2  0.642804  0.000000 -1.628695
3  0.501038  0.000000  1.832153
4  2.847076 -0.176141 -0.543126
5 -0.018326 -0.100503 -1.181996
6  0.131721  0.314774  2.846230

In [23]:
#! ipython id=a03bb4bc12e24a3e941daa79068471ff
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.238404  0.500000  0.000000
1 -1.044114  0.500000  0.000000
2  0.642804  0.500000 -1.628695
3  0.501038  0.500000  1.832153
4  2.847076 -0.176141 -0.543126
5 -0.018326 -0.100503 -1.181996
6  0.131721  0.314774  2.846230

In [24]:
#! ipython id=bf828716b9e04ef5a37200b5d5086b47
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df


0         1         2
0 -0.834215  2.014782 -1.810094
1  0.517489  0.118850 -0.319411
2 -0.374644       NaN -0.271652
3  0.222970       NaN -0.071291
4 -1.964290       NaN       NaN
5  0.544878       NaN       NaN

In [25]:
df.fillna(method="ffill")


0         1         2
0 -0.834215  2.014782 -1.810094
1  0.517489  0.118850 -0.319411
2 -0.374644  0.118850 -0.271652
3  0.222970  0.118850 -0.071291
4 -1.964290  0.118850 -0.071291
5  0.544878  0.118850 -0.071291

In [26]:
df.fillna(method="ffill", limit=2)

0         1         2
0 -0.834215  2.014782 -1.810094
1  0.517489  0.118850 -0.319411
2 -0.374644  0.118850 -0.271652
3  0.222970  0.118850 -0.071291
4 -1.964290       NaN -0.071291
5  0.544878       NaN -0.071291

In [27]:
#! ipython id=77b2b4714bd14dffb5e6b407fd0df952
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [28]:
#! ipython id=944377d16cdc466cb0a9e64fa1f79d5b
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [29]:
#! ipython id=bd2994de11fd4012a835bd0ee2bcf4cb
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [30]:
#! ipython id=ac1c8d333c8d40068f33556cee5cb8b4
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [31]:
#! ipython id=ac73e11080b04551bdf1a23729e75793
data["v1"] = range(7)
data


k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [32]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [33]:
#! ipython id=eb735c97c9b744aa923b8fb94ae22f64
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [34]:
#! ipython id=4fd09f7a425741d5b1f61a28f2ec73a2
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [36]:
#! ipython verbatim id=1459d863e4e2488884aa21b5841fa88d
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [37]:
#! ipython id=a779fa7330de487fb907e801bf054696
data["animal"] = data["food"].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [38]:
#! ipython id=4c24af18964744eda625a480f5cdd126
def get_animal(x):
    return meat_to_animal[x]
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [40]:
data['food'].map(lambda x: meat_to_animal[x])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [41]:
#! ipython id=ec9f0e43f8da42ed8b3119331d09c853
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [42]:
#! ipython id=8fd47d92ab854f47bed89d8a72c9d8a0
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [43]:
#! ipython id=6bd3f8909caf4eed928f7164f277f8ef
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [44]:
#! ipython id=467da543042d473aa9ed8b43e5daefec
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [45]:
#! ipython id=e3dfba217f5a460d9bdf04ba573481ad
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [46]:
#! ipython id=103a514cd451404fbc7b559bab5ea87c
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])

In [47]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [48]:
#! ipython id=aabdeea6a25f49a5a6949527b7d345bb
def transform(x):
    return x[:4].upper()

data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [49]:
transform2 = lambda x: x[:4].upper()
data.index.map(transform2)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [50]:
#! ipython id=8923ced04de44246b6d710395cc93348
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [51]:
#! ipython id=d125b3401a124c89a83007e36e3ee758
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [52]:
#! ipython id=5f8e0d6ff0b4445d886c8ee0fb478191
data.rename(index={"OHIO": "INDIANA"},
            columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [53]:
#! ipython id=5b066323cc4944c9938b36f4f8d52779
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [54]:
#! ipython id=075935d1c34b41ba9ee1842e23605ad1
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [55]:
#! ipython id=ce9e07485ac641e291688784a05e841c
age_categories.codes


array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [56]:
age_categories.categories


IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [57]:
age_categories.categories[0]


Interval(18, 25, closed='right')

In [58]:
pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [59]:
#! ipython id=c40f7922de224c5682b37159bfb13adf
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [60]:
#! ipython id=5d5d56eba8384d11bd5d38c378c9fbf1
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [61]:
#! ipython id=33190ad9f1834874ba7cbd4066d8350b
data = np.random.uniform(size=20)
pd.cut(data, 4, precision=2)

[(0.061, 0.29], (0.52, 0.75], (0.29, 0.52], (0.29, 0.52], (0.75, 0.98], ..., (0.52, 0.75], (0.75, 0.98], (0.75, 0.98], (0.061, 0.29], (0.061, 0.29]]
Length: 20
Categories (4, interval[float64, right]): [(0.061, 0.29] < (0.29, 0.52] < (0.52, 0.75] < (0.75, 0.98]]

In [62]:
#! ipython id=5aa787199f2745d1a2358a097e9b23d9
data = np.random.standard_normal(1000)
quartiles = pd.qcut(data, 4, precision=2)
quartiles


[(0.041, 0.63], (-2.6199999999999997, -0.68], (0.041, 0.63], (-0.68, 0.041], (-2.6199999999999997, -0.68], ..., (-0.68, 0.041], (0.041, 0.63], (0.041, 0.63], (0.041, 0.63], (-0.68, 0.041]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.6199999999999997, -0.68] < (-0.68, 0.041] < (0.041, 0.63] < (0.63, 3.0]]

In [63]:
pd.value_counts(quartiles)

(-2.6199999999999997, -0.68]    250
(-0.68, 0.041]                  250
(0.041, 0.63]                   250
(0.63, 3.0]                     250
dtype: int64

In [64]:
#! ipython id=6df8a2f012ad4735bbc92d478d946e1f
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.608, -1.317]    100
(-1.317, 0.0409]    400
(0.0409, 1.24]      400
(1.24, 3.003]       100
dtype: int64

In [65]:
#! ipython id=3979599fd2d247b7a32bf203a5c9a5c7
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.021076    -0.036899     0.021775     0.004258
std       1.012321     1.024136     0.986254     0.999700
min      -4.076602    -3.347987    -3.449849    -2.952336
25%      -0.634914    -0.746991    -0.648937    -0.652232
50%      -0.007965    -0.017650     0.051529     0.014932
75%       0.655220     0.623500     0.696768     0.674236
max       2.929657     3.090810     3.577681     3.174948

In [68]:
#! ipython id=14662c0a588c488d83d792107f20e528
col = data[2]
col[np.abs(col) > 3]

47    -3.449849
162    3.051112
450    3.577681
543   -3.047477
822    3.119261
Name: 2, dtype: float64

In [69]:
#! ipython id=2a1bb1c468cf40a58f3c5223a992b59b
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
47  -1.339083  0.724467 -3.449849  0.322400
159  1.156957 -0.925428 -0.824364  3.138540
162 -0.358164 -0.798112  3.051112  0.126011
303 -1.039134  0.831562 -1.467905  3.174948
404 -1.168473 -3.347987 -1.437937 -0.704557
450  2.377839 -0.596827  3.577681  0.432449
487  0.797402 -3.033291  0.754801  0.363531
543  0.458445  1.737691 -3.047477 -0.401304
563 -3.200353  0.877457  0.957310  3.134567
581  0.271749  3.090810 -0.139691 -1.346885
651 -4.076602  0.485151  1.114157  0.037315
822 -0.876989  0.277855  3.119261  1.262249
993 -0.781417 -3.172215 -0.668082  1.748114

In [70]:
data[(data.abs() > 3).any(1)]

0         1         2         3
47  -1.339083  0.724467 -3.449849  0.322400
159  1.156957 -0.925428 -0.824364  3.138540
162 -0.358164 -0.798112  3.051112  0.126011
303 -1.039134  0.831562 -1.467905  3.174948
404 -1.168473 -3.347987 -1.437937 -0.704557
450  2.377839 -0.596827  3.577681  0.432449
487  0.797402 -3.033291  0.754801  0.363531
543  0.458445  1.737691 -3.047477 -0.401304
563 -3.200353  0.877457  0.957310  3.134567
581  0.271749  3.090810 -0.139691 -1.346885
651 -4.076602  0.485151  1.114157  0.037315
822 -0.876989  0.277855  3.119261  1.262249
993 -0.781417 -3.172215 -0.668082  1.748114

In [71]:
#! ipython id=694246321bbd42adbb221b99486f388b
data[data.abs() > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.019799    -0.036436     0.021524     0.003810
std       1.007957     1.022183     0.982177     0.998321
min      -3.000000    -3.000000    -3.000000    -2.952336
25%      -0.634914    -0.746991    -0.648937    -0.652232
50%      -0.007965    -0.017650     0.051529     0.014932
75%       0.655220     0.623500     0.696768     0.674236
max       2.929657     3.000000     3.000000     3.000000

In [72]:
#! ipython id=d70c02173fe945abad1450a5709b520e
np.sign(data).head()

0    1    2    3
0 -1.0  1.0  1.0  1.0
1 -1.0 -1.0  1.0 -1.0
2 -1.0  1.0 -1.0 -1.0
3  1.0 -1.0  1.0  1.0
4  1.0 -1.0  1.0  1.0

In [73]:
#! ipython id=70d08ca5f48d48018126fd9ab1006314
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
df
sampler = np.random.permutation(5)
sampler

array([2, 0, 1, 4, 3])

In [74]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [75]:
#! ipython id=f7c2008d514b4a549645c2c8a28861d9
df.take(sampler)


0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27

In [76]:
df.iloc[sampler]

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27

In [79]:
df.sample(n=3)

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13

In [80]:
#! ipython id=ffbccf111b60408395f9eb116f6fc39a
column_sampler = np.random.permutation(7)
column_sampler


array([0, 4, 3, 6, 5, 1, 2])

In [81]:
df.take(column_sampler, axis="columns")

0   4   3   6   5   1   2
0   0   4   3   6   5   1   2
1   7  11  10  13  12   8   9
2  14  18  17  20  19  15  16
3  21  25  24  27  26  22  23
4  28  32  31  34  33  29  30

In [82]:
#! ipython id=c2429f2bce484acca0f590eed87cb896
df.sample(n=3)

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13

In [83]:
#! ipython id=f98970c0ba4942d880cf0d4076960bc3
choices = pd.Series([5, 7, -1, 6, 4])

choices.sample(n=10, replace=True)

1    7
0    5
2   -1
3    6
3    6
0    5
0    5
1    7
3    6
4    4
dtype: int64

In [84]:
#! ipython id=590105f5b54b4b798b9c925339f1c000
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})
df


key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [85]:
pd.get_dummies(df["key"])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [86]:
#! ipython id=c9bf047cafa2489cb537d963eb18d16a
dummies = pd.get_dummies(df["key"], prefix="key")
df_with_dummy = df[["data1"]].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [87]:
#! ipython allow_exceptions id=e311a84ee00c40479411ed79fc5a6c69
mnames = ["movie_id", "title", "genres"]
movies = pd.read_table("datasets/movielens/movies.dat", sep="::",
                       header=None, names=mnames, engine="python")
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [88]:
all_genres = []

In [89]:
for x in movies.genres:
    all_genres.extend(x.split('|'))
    

In [90]:
genres=pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [94]:
zero_matrix = np.zeros((len(movies), len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres)
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
1           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
2           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
4           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    0.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [96]:
gen=movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [97]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [91]:
#! ipython id=8e085399c22341ee9632bf5efcb4a6dc
dummies = movies["genres"].str.get_dummies("|")
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [98]:
#! ipython id=9b2a0b211d424f6798485b72bd572e08
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                              0.0
Genre_Children's                             0.0
Genre_Comedy                                 0.0
Genre_Adventure                              0.0
Genre_Fantasy                                0.0
Genre_Romance                                0.0
Genre_Drama                                  0.0
Genre_Action                                 0.0
Genre_Crime                                  0.0
Genre_Thriller                               0.0
Genre_Horror                                 0.0
Genre_Sci-Fi                                 0.0
Genre_Documentary                            0.0
Genre_War                                    0.0
Genre_Musical                                0.0
Genre_Mystery                                0.0
Genre_Film-Noir                              0.0
Genre_Western       

In [99]:
#! ipython id=f3df965a3e024e918c1e67e647a6589a
np.random.seed(12345) # to make the example repeatable
values = np.random.uniform(size=10)
values


array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [100]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [103]:
#! ipython id=10771102e8084f5fa4a16200a93d058d
s = pd.Series([1, 2, 3, None])
s
s.dtype

dtype('float64')

In [105]:
#! ipython id=66923eb117b34b21b548507e349d387d
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())
s
s.isna()
s.dtype

Int64Dtype()

In [108]:
#! ipython id=8a80094d8808433599836ea7197e55b9
s[3]
s[3] is pd.NA

True

In [109]:
#! ipython id=43b53a40545c451c94728b65b40c574e
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [110]:
#! ipython id=85af440e08ae45d9b570c8b65f496567
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [111]:
#! ipython id=81a4d68317534367bdbd458b98a55329
df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})
df


A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [112]:
df["A"] = df["A"].astype("Int64")
df["B"] = df["B"].astype("string")
df["C"] = df["C"].astype("boolean")
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

In [113]:
#! ipython id=fe9efc6724224b7b9eccd32750524def
val = "a,b,  guido"
val.split(",")

['a', 'b', '  guido']

In [114]:
#! ipython id=9724ab6a052943e7803c2f855b47b29f
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [115]:
#! ipython id=e80b9a9828014622b86c088759d5e5a0
first, second, third = pieces
first + "::" + second + "::" + third

'a::b::guido'

In [116]:
#! ipython id=06baf1c7f132476f90f73524278f5972
"::".join(pieces)

'a::b::guido'

In [118]:
#! ipython id=d5571ea9402c4182af832d4b0b659ad4
"guido" in val


True

In [119]:
val.index(",")


1

In [120]:
val.find(":")

-1

In [121]:
#! ipython allow_exceptions id=ee7ecc7978534b3883cf050a76245ba3
val.index(":")

ValueError: substring not found

In [122]:
#! ipython id=6c3ac8963e0348d5900d3b21f3d61421
val.count(",")

2

In [123]:
#! ipython id=2385159093a248abbb0b590843359737
val.replace(",", "::")


'a::b::  guido'

In [124]:
val.replace(",", "")

'ab  guido'

In [1]:
#! ipython id=b430b6ee3c904fa38a207e995ad4e152
import re
text = "foo    bar\t baz  \tqux"
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [2]:
#! ipython id=2af33f0f709d42a2853daaabafede024
regex = re.compile(r"\s+")
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [3]:
#! ipython id=746b726a56dd4375a8a459b74d65789c
regex.findall(text)

['    ', '\t ', '  \t']

In [5]:
#! ipython verbatim id=8f2d09408b41491aa269044fc4375d93
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE makes the regex case insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

In [6]:
#! ipython id=4efa726d3118445db3dfa63e69147a3e
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [7]:
#! ipython id=5d3ea127f5064a0eabafa8f07982c0fe
m = regex.search(text)
m
text[m.start():m.end()]

'dave@google.com'

In [8]:
#! ipython id=56352eb1b66041658dc4a2df7cdd3659
print(regex.match(text))

None


In [9]:
#! ipython id=16b2b19e1790421f8cbfd96272f49964
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [10]:
#! ipython id=48a7da4e764149fc9fbbc73d8836e703
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern, flags=re.IGNORECASE)

In [11]:
#! ipython id=0e0269c4dfb748a787340d99bd51af16
m = regex.match("wesm@bright.net")
m.groups()

('wesm', 'bright', 'net')

In [12]:
#! ipython id=ba6371f22b31476d99904236e025caf2
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [13]:
#! ipython id=adf56cb7344246a4981c9ccbc4520e45
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


In [28]:
#! ipython id=d2dae337d0724a7cabb69f0d2e45d21a
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}
data = pd.Series(data)
data


Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [29]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [30]:
#! ipython id=b1a32c08159845ad97915762d2e9104c
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [32]:
#! ipython id=e83b7f3cb11b42ea8344da39bc8313ed
data_as_string_ext = data.astype('string')
data_as_string_ext


Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [33]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [34]:
#! ipython id=abd3d1bd7239406d8d764f812cb04018
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [35]:
#! ipython id=07c02acaf03844578f9b18af036e96b4
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]
matches


Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [36]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [38]:
matches.str[0]

Dave      dave
Steve    steve
Rob        rob
Wes        NaN
dtype: object

In [37]:
#! ipython id=140f72f7ebdf44fc832ac76596f1f500
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [39]:
#! ipython id=086c74fc48364b859ab30d4c9278e96d
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [44]:
#! ipython id=5e0d1d0145d64d80870482f06001910e
values = pd.Series(['apple', 'orange', 'apple',
                    'apple'] * 2)
values



0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [45]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [43]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [54]:
#! ipython id=6b72957b5a1c4882828b5b6fc55bc645
values = pd.Series([0, 1, 0, 0] * 2)
dim = pd.Series(['apple', 'orange'])
values


0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [53]:
dim

0     apple
1    orange
dtype: object

In [51]:
#! ipython id=c4c6450bbb7f4c74b579d4cc989d0547
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [55]:
#! ipython id=922c7a3dfaf5478c8ece876bf6e8c8a4
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [56]:
#! ipython id=d3efa50a15b64f78b8ee5d1bffd9e3db
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [57]:
#! ipython id=5b3590609c7f4a2984add7aefc62727c
c = fruit_cat.array
type(c)

pandas.core.arrays.categorical.Categorical

In [59]:
#! ipython id=4d5fd7e39e7b4dc4bf59a7597a66cbe1
c.categories


Index(['apple', 'orange'], dtype='object')

In [60]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [61]:
#! ipython id=a5d2afb03a3d46fe99b79633b5480fb7
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [62]:
#! ipython id=b4e849ae87304ac1a2b717ecafbf58c4
df['fruit'] = df['fruit'].astype('category')
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [63]:
#! ipython id=adba8c41d0094e49943f4c0f03bfb560
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [64]:
#! ipython id=dbb5b2424ba146f0b001398542f64ae3
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]
my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [65]:
#! ipython id=2ee990370ede41ddbcf285a6c1330ee0
ordered_cat = pd.Categorical.from_codes(codes, categories,
                                        ordered=True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [66]:
#! ipython id=27e720c7999143b8bc6fa95797bb78fd
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [67]:
#! ipython id=3268082ea833473888cb6df910208de8
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [71]:
#! ipython id=6d7daaf08a8240dea51848a3a6cc211d
bins = pd.qcut(draws, 4)
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [72]:
#! ipython id=6faabc704b9c436fa0e32ac6755e6359
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [73]:
#! ipython id=0f2080e060dd4d848ff1a9d846c8a71e
bins = pd.Series(bins, name='quartile')
results = (pd.Series(draws)
           .groupby(bins)
           .agg(['count', 'min', 'max'])
           .reset_index())
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [74]:
#! ipython id=4d1f92dfe8e34a6d8173c0aca18d8b55
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [75]:
#! ipython id=cb512af2f6bf4eb5b312ae330bd4c91e
N = 10_000_000
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [76]:
#! ipython id=2978248572a743be8529a1668d424e8a
categories = labels.astype('category')

In [77]:
#! ipython id=a16f1610329347ffa2f28661941350b7
labels.memory_usage(deep=True)
categories.memory_usage(deep=True)

10000540

In [91]:
#! ipython id=dd7310d96d4d4c24bb7e3e9ad26b066f
%time _ = labels.astype('category')

CPU times: total: 1.02 s
Wall time: 1.02 s


In [92]:
#! ipython id=aca60c356d264f7c872287f1bfdf75c9
%timeit labels.value_counts()
%timeit categories.value_counts()

749 ms ± 27.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
139 ms ± 14.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [78]:
#! ipython id=9dd1c0395c0743db8a283da215ae7f50
s = pd.Series(['a', 'b', 'c', 'd'] * 2)
cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [89]:
#! ipython id=84308427acbc491381531a16cd3bcc15
cat_s.cat.codes


0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [90]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [80]:
#! ipython id=7b07ac0b91ef42809b1183ccc41555c1
actual_categories = ['a', 'b', 'c', 'd', 'e']
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [87]:
#! ipython id=919709709a4c4c8d93e135d137ea0757
cat_s.value_counts()


a    2
b    2
c    2
d    2
dtype: int64

In [88]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
dtype: int64

In [85]:
#! ipython id=0350789cd1fe41c6908b5e604ea34eb0
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]
cat_s3


0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [86]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [83]:
#! ipython id=c6b7347f928a4580b5dac67f798d9e28
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [84]:
#! ipython id=95950502e1bc4cfba88e7891c8062ee6
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1

In [93]:
#! ipython suppress id=b8746f91160c4c9da000aeb4891514bf
%popd

UsageError: %popd on empty stack


In [94]:
#! ipython suppress id=621a2c4436a44e5db40091b1e4f8a167
pd.options.display.max_rows = PREVIOUS_MAX_ROWS

NameError: name 'PREVIOUS_MAX_ROWS' is not defined