In [1]:
#! ipython suppress id=379207b8b8f44b8c8e923bccddb74e1b
%pushd book-materials
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision=4, suppress=True)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [188]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [189]:
pd.unique(values)


array(['apple', 'orange'], dtype=object)

In [12]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [35]:
#datawarehouse dimensios tables distinct values
values = pd.Series([0, 1, 0, 0]*2)
dim = pd.Series(['apple', 'orange'])

In [36]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [37]:
dim

0     apple
1    orange
dtype: object

In [38]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [43]:
#categorical Type in pandas
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
df = pd.DataFrame({'fruit': fruits,
                  'basket_id': np.arange(N),
                  'count': np.random.randint(2, 15, size=N),
                  'weight': np.random.uniform(0, 4, size=N)},
                 columns=['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     14  2.565277
1          1  orange      7  2.808423
2          2   apple     11  1.231458
3          3   apple      2  1.579336
4          4   apple     13  0.139228
5          5  orange     10  0.038288
6          6   apple      8  3.819268
7          7   apple     10  1.458095

In [53]:
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [54]:
c= fruit_cat.values
type(c)

pandas.core.arrays.categorical.Categorical

In [55]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [56]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [58]:
df['fruit'] = df['fruit'].astype('category')
df.fruit

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [59]:
my_categories = pd.Categorical(['foo', 'bar', 'baz','foo', 'bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [62]:
categories =['foo', 'bar', 'baz']
codes =[0,1,2,0,0,1]
my_cat_2= pd.Categorical.from_codes(codes, categories)
my_cat_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [64]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [66]:
my_cat_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [70]:
np.random.seed(12345)
draws = np.random.randn(1000)
draws[:5]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057])

In [72]:
bins = pd.qcut(draws, 4)
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [73]:
bins = pd.qcut(draws, 4, labels =['Q1', 'Q2', 'Q3', 'Q4'])
bins

['Q2', 'Q3', 'Q2', 'Q2', 'Q4', ..., 'Q3', 'Q2', 'Q1', 'Q3', 'Q4']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [74]:
bins.codes[:10]

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3], dtype=int8)

In [76]:
bins = pd.Series(bins, name='quartile')
results = (pd.Series(draws)
          .groupby(bins)
          .agg(['count', 'min',  'max'])
          .reset_index())
results

quartile  count       min       max
0       Q1    250 -2.949343 -0.685484
1       Q2    250 -0.683066 -0.010115
2       Q3    250 -0.010032  0.628894
3       Q4    250  0.634238  3.927528

In [77]:
N=10000000
draws = pd.Series(np.random.randn(N))
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N//4))

In [78]:
categories = labels.astype('category')
categories

0          foo
1          bar
2          baz
3          qux
4          foo
          ... 
9999995    qux
9999996    foo
9999997    bar
9999998    baz
9999999    qux
Length: 10000000, dtype: category
Categories (4, object): ['bar', 'baz', 'foo', 'qux']

In [80]:
labels.memory_usage()

80000128

In [81]:
categories.memory_usage()

10000332

In [85]:
%time _ = labels.astype('category')

CPU times: total: 1.08 s
Wall time: 1.16 s


In [88]:
s = pd.Series(['a', 'b', 'c', 'd']*2)
cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [89]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [91]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [98]:
atual_categorias = ['a','b','c','d','e']
cat_s2=cat_s.cat.set_categories(atual_categorias)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [95]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
dtype: int64

In [97]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
dtype: int64

In [100]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [101]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [102]:
cat_s = pd.Series(['a', 'b', 'c', 'd']  * 2, dtype='category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [103]:
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1

In [105]:
df = pd.DataFrame({'key': ['a', 'b', 'c'] * 4,'value': np.arange(12.)})
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [108]:
g = df.groupby('key').value
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [109]:
g.transform(lambda x: x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [110]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [111]:
g.transform(lambda x: x*2)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [112]:
g.transform(lambda x: x.rank(ascending=False))

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [113]:
def normalize(x):
    return (x-x.mean()) / x.std()

In [115]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [117]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [118]:
normalized = (df['value'] - g.transform('mean'))/ g.transform('std')
normalized

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [120]:
N = 15

times = pd.date_range('2017-05-20 00:00' , freq='1min', periods=N)
times

DatetimeIndex(['2017-05-20 00:00:00', '2017-05-20 00:01:00',
               '2017-05-20 00:02:00', '2017-05-20 00:03:00',
               '2017-05-20 00:04:00', '2017-05-20 00:05:00',
               '2017-05-20 00:06:00', '2017-05-20 00:07:00',
               '2017-05-20 00:08:00', '2017-05-20 00:09:00',
               '2017-05-20 00:10:00', '2017-05-20 00:11:00',
               '2017-05-20 00:12:00', '2017-05-20 00:13:00',
               '2017-05-20 00:14:00'],
              dtype='datetime64[ns]', freq='T')

In [122]:
df = pd.DataFrame({'time': times, 'value': np.arange(N)})
df

time  value
0  2017-05-20 00:00:00      0
1  2017-05-20 00:01:00      1
2  2017-05-20 00:02:00      2
3  2017-05-20 00:03:00      3
4  2017-05-20 00:04:00      4
5  2017-05-20 00:05:00      5
6  2017-05-20 00:06:00      6
7  2017-05-20 00:07:00      7
8  2017-05-20 00:08:00      8
9  2017-05-20 00:09:00      9
10 2017-05-20 00:10:00     10
11 2017-05-20 00:11:00     11
12 2017-05-20 00:12:00     12
13 2017-05-20 00:13:00     13
14 2017-05-20 00:14:00     14

In [123]:
df.set_index('time').resample('5min').count()

value
time                      
2017-05-20 00:00:00      5
2017-05-20 00:05:00      5
2017-05-20 00:10:00      5

In [124]:
df2 = pd.DataFrame({'time': times.repeat(3),
      'key': np.tile(['a', 'b', 'c'], N),
      'value': np.arange(N * 3.)})
df2

time key  value
0  2017-05-20 00:00:00   a    0.0
1  2017-05-20 00:00:00   b    1.0
2  2017-05-20 00:00:00   c    2.0
3  2017-05-20 00:01:00   a    3.0
4  2017-05-20 00:01:00   b    4.0
5  2017-05-20 00:01:00   c    5.0
6  2017-05-20 00:02:00   a    6.0
7  2017-05-20 00:02:00   b    7.0
8  2017-05-20 00:02:00   c    8.0
9  2017-05-20 00:03:00   a    9.0
10 2017-05-20 00:03:00   b   10.0
11 2017-05-20 00:03:00   c   11.0
12 2017-05-20 00:04:00   a   12.0
13 2017-05-20 00:04:00   b   13.0
14 2017-05-20 00:04:00   c   14.0
15 2017-05-20 00:05:00   a   15.0
16 2017-05-20 00:05:00   b   16.0
17 2017-05-20 00:05:00   c   17.0
18 2017-05-20 00:06:00   a   18.0
19 2017-05-20 00:06:00   b   19.0
20 2017-05-20 00:06:00   c   20.0
21 2017-05-20 00:07:00   a   21.0
22 2017-05-20 00:07:00   b   22.0
23 2017-05-20 00:07:00   c   23.0
24 2017-05-20 00:08:00   a   24.0
25 2017-05-20 00:08:00   b   25.0
26 2017-05-20 00:08:00   c   26.0
27 2017-05-20 00:09:00   a   27.0
28 2017-05-20 00:09:00   b   28.0
29 2017-05-20 00:09:00   c   29.0
30 2017-05-20 00:10:00   a   30.0
31 2017-05-20 00:10:00   b   31.0
32 2017-05-20 00:10:00   c   32.0
33 2017-05-20 00:11:00   a   33.0
34 2017-05-20 00:11:00   b   34.0
35 2017-05-20 00:11:00   c   35.0
36 2017-05-20 00:12:00   a   36.0
37 2017-05-20 00:12:00   b   37.0
38 2017-05-20 00:12:00   c   38.0
39 2017-05-20 00:13:00   a   39.0
40 2017-05-20 00:13:00   b   40.0
41 2017-05-20 00:13:00   c   41.0
42 2017-05-20 00:14:00   a   42.0
43 2017-05-20 00:14:00   b   43.0
44 2017-05-20 00:14:00   c   44.0

In [125]:
df[:7]

time  value
0 2017-05-20 00:00:00      0
1 2017-05-20 00:01:00      1
2 2017-05-20 00:02:00      2
3 2017-05-20 00:03:00      3
4 2017-05-20 00:04:00      4
5 2017-05-20 00:05:00      5
6 2017-05-20 00:06:00      6

In [135]:
from pandas.core.resample import DatetimeIndex, TimeGrouper

time_key = TimeGrouper('5min')

In [134]:
resampled = (df2.set_index('time')
      .groupby(['key', time_key])
      .sum())

In [136]:
resampled

value
key time                      
a   2017-05-20 00:00:00   30.0
    2017-05-20 00:05:00  105.0
    2017-05-20 00:10:00  180.0
b   2017-05-20 00:00:00   35.0
    2017-05-20 00:05:00  110.0
    2017-05-20 00:10:00  185.0
c   2017-05-20 00:00:00   40.0
    2017-05-20 00:05:00  115.0
    2017-05-20 00:10:00  190.0

In [143]:
resampled.reset_index()

key                time  value
0   a 2017-05-20 00:00:00   30.0
1   a 2017-05-20 00:05:00  105.0
2   a 2017-05-20 00:10:00  180.0
3   b 2017-05-20 00:00:00   35.0
4   b 2017-05-20 00:05:00  110.0
5   b 2017-05-20 00:10:00  185.0
6   c 2017-05-20 00:00:00   40.0
7   c 2017-05-20 00:05:00  115.0
8   c 2017-05-20 00:10:00  190.0

In [146]:
#metodo de cadeia
df = pd.read_csv('examples/tips.csv')
df

total_bill   tip smoker   day    time  size
0         16.99  1.01     No   Sun  Dinner     2
1         10.34  1.66     No   Sun  Dinner     3
2         21.01  3.50     No   Sun  Dinner     3
3         23.68  3.31     No   Sun  Dinner     2
4         24.59  3.61     No   Sun  Dinner     4
..          ...   ...    ...   ...     ...   ...
239       29.03  5.92     No   Sat  Dinner     3
240       27.18  2.00    Yes   Sat  Dinner     2
241       22.67  2.00    Yes   Sat  Dinner     2
242       17.82  1.75     No   Sat  Dinner     2
243       18.78  3.00     No  Thur  Dinner     2

[244 rows x 6 columns]

In [9]:
#! ipython id=6b91a5404025497cb8caca631d473d94
data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.]} )
data


x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [193]:
data.columns


Index(['x0', 'x1', 'y'], dtype='object')

In [194]:
data.values

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [5]:
data.to_numpy()

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [195]:
#! ipython id=bd1bb62fd48f4d1d8c0fa538775d33fa
df2 = pd.DataFrame(data.to_numpy(), columns=['one', 'two', 'three'])
df2

one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [196]:
#! ipython id=eb72464446b24feab231e6d154a13d68
df3 = data.copy()
df3['strings'] = ['a', 'b', 'c', 'd', 'e']
df3


x0    x1    y strings
0   1  0.01 -1.5       a
1   2 -0.01  0.0       b
2   3  0.25  3.6       c
3   4 -4.10  1.3       d
4   5  0.00 -2.0       e

In [197]:
df3.to_numpy()

array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.0, 'e']], dtype=object)

In [198]:
df3.values


array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.0, 'e']], dtype=object)

In [199]:
#! ipython id=0284bd81d9734d62a0d2dcb8fc65e935
model_cols = ['x0', 'x1']
data.loc[:, model_cols].to_numpy()

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [200]:
#! ipython id=7b7d579912624331ac4bd2bf08470533
data['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'],
                                  categories=['a', 'b'])
data

x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

In [201]:
#! ipython id=361dec779b57482b94be56e2d062e793
dummies = pd.get_dummies(data.category, prefix='category')


In [202]:
data_with_dummies = data.drop('category', axis=1).join(dummies)


In [203]:
data_with_dummies

x0    x1    y  category_a  category_b
0   1  0.01 -1.5           1           0
1   2 -0.01  0.0           0           1
2   3  0.25  3.6           1           0
3   4 -4.10  1.3           1           0
4   5  0.00 -2.0           0           1

In [204]:
#! ipython id=0f377070f0d14b769232b62284a278f4
data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.]})
data
import patsy
y, X = patsy.dmatrices('y ~ x0 + x1', data)

In [205]:
#! ipython id=5252acd3c6db4a3d9af0ebbb309c28c1
y


DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [206]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [207]:
#! ipython id=03adb0f4a90247f6aba11e6763b806d0
np.asarray(y)


array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

In [208]:
np.asarray(X)

array([[ 1.  ,  1.  ,  0.01],
       [ 1.  ,  2.  , -0.01],
       [ 1.  ,  3.  ,  0.25],
       [ 1.  ,  4.  , -4.1 ],
       [ 1.  ,  5.  ,  0.  ]])

In [209]:
#! ipython id=a3a80cb56c54468b9e26c4cb052b5f6a
patsy.dmatrices('y ~ x0 + x1 + 0', data)[1]

DesignMatrix with shape (5, 2)
  x0     x1
   1   0.01
   2  -0.01
   3   0.25
   4  -4.10
   5   0.00
  Terms:
    'x0' (column 0)
    'x1' (column 1)

In [218]:
#! ipython id=db616433095b4c758545ec95c5ba56d4
coef, resid, _, _ = np.linalg.lstsq(X, y, rcond=None)

In [219]:
#! ipython id=a02f213f2f10477b8b7907c83746bbc6
coef


array([[ 0.31290976],
       [-0.07910564],
       [-0.26546384]])

In [220]:
coef = pd.Series(coef.squeeze(), index=X.design_info.column_names)
coef

Intercept    0.312910
x0          -0.079106
x1          -0.265464
dtype: float64

In [221]:
#! ipython id=0da24c4c7d374bb0b2cac75072a4dd04
y, X = patsy.dmatrices('y ~ x0 + np.log(np.abs(x1) + 1)', data)
X

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1) + 1)
          1   1                 0.00995
          1   2                 0.00995
          1   3                 0.22314
          1   4                 1.62924
          1   5                 0.00000
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1) + 1)' (column 2)

In [222]:
#! ipython id=eed36a4a619c4d9f9d65c0d8cb19d34e
y, X = patsy.dmatrices('y ~ standardize(x0) + center(x1)', data)
X

DesignMatrix with shape (5, 3)
  Intercept  standardize(x0)  center(x1)
          1         -1.41421        0.78
          1         -0.70711        0.76
          1          0.00000        1.02
          1          0.70711       -3.33
          1          1.41421        0.77
  Terms:
    'Intercept' (column 0)
    'standardize(x0)' (column 1)
    'center(x1)' (column 2)

In [223]:
#! ipython id=88739eb5eaa94ab0bb19779111888158
new_data = pd.DataFrame({
    'x0': [6, 7, 8, 9],
    'x1': [3.1, -0.5, 0, 2.3],
    'y': [1, 2, 3, 4]})
new_X = patsy.build_design_matrices([X.design_info], new_data)
new_X

[DesignMatrix with shape (4, 3)
   Intercept  standardize(x0)  center(x1)
           1          2.12132        3.87
           1          2.82843        0.27
           1          3.53553        0.77
           1          4.24264        3.07
   Terms:
     'Intercept' (column 0)
     'standardize(x0)' (column 1)
     'center(x1)' (column 2)]

In [224]:
#! ipython id=766fcf4390d24922a9f4cbbf86da6870
y, X = patsy.dmatrices('y ~ I(x0 + x1)', data)
X

DesignMatrix with shape (5, 2)
  Intercept  I(x0 + x1)
          1        1.01
          1        1.99
          1        3.25
          1       -0.10
          1        5.00
  Terms:
    'Intercept' (column 0)
    'I(x0 + x1)' (column 1)

In [225]:
#! ipython id=5fa5d310160a4cd7a5862986a6be9c3d
data = pd.DataFrame({
    'key1': ['a', 'a', 'b', 'b', 'a', 'b', 'a', 'b'],
    'key2': [0, 1, 0, 1, 0, 1, 0, 0],
    'v1': [1, 2, 3, 4, 5, 6, 7, 8],
    'v2': [-1, 0, 2.5, -0.5, 4.0, -1.2, 0.2, -1.7]
})
y, X = patsy.dmatrices('v2 ~ key1', data)
X

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

In [226]:
#! ipython id=d795962e76ab48f7bbd08fa3adc3f481
y, X = patsy.dmatrices('v2 ~ key1 + 0', data)
X

DesignMatrix with shape (8, 2)
  key1[a]  key1[b]
        1        0
        1        0
        0        1
        0        1
        1        0
        0        1
        1        0
        0        1
  Terms:
    'key1' (columns 0:2)

In [227]:
#! ipython id=2619ef96053c43eeb4f0fbaa5aed3836
y, X = patsy.dmatrices('v2 ~ C(key2)', data)
X

DesignMatrix with shape (8, 2)
  Intercept  C(key2)[T.1]
          1             0
          1             1
          1             0
          1             1
          1             0
          1             1
          1             0
          1             0
  Terms:
    'Intercept' (column 0)
    'C(key2)' (column 1)

In [228]:
#! ipython id=6efd1f19da93449d8ae591df85a826c9
data['key2'] = data['key2'].map({0: 'zero', 1: 'one'})
data


key1  key2  v1   v2
0    a  zero   1 -1.0
1    a   one   2  0.0
2    b  zero   3  2.5
3    b   one   4 -0.5
4    a  zero   5  4.0
5    b   one   6 -1.2
6    a  zero   7  0.2
7    b  zero   8 -1.7

In [229]:
y, X = patsy.dmatrices('v2 ~ key1 + key2', data)
X


DesignMatrix with shape (8, 3)
  Intercept  key1[T.b]  key2[T.zero]
          1          0             1
          1          0             0
          1          1             1
          1          1             0
          1          0             1
          1          1             0
          1          0             1
          1          1             1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)

In [230]:
y, X = patsy.dmatrices('v2 ~ key1 + key2 + key1:key2', data)
X

DesignMatrix with shape (8, 4)
  Intercept  key1[T.b]  key2[T.zero]  key1[T.b]:key2[T.zero]
          1          0             1                       0
          1          0             0                       0
          1          1             1                       1
          1          1             0                       0
          1          0             1                       0
          1          1             0                       0
          1          0             1                       0
          1          1             1                       1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)
    'key1:key2' (column 3)

In [231]:
#! ipython verbatim id=2c6c970ee0234156b7dea4ebb8b16790
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [232]:
#! ipython verbatim id=15d197f427b344fa9f456841b129b9e4
# To make the example reproducible
rng = np.random.default_rng(seed=12345)

def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size = size,
    return mean + np.sqrt(variance) * rng.standard_normal(*size)

N = 100
X = np.c_[dnorm(0, 0.4, size=N),
          dnorm(0, 0.6, size=N),
          dnorm(0, 0.2, size=N)]
eps = dnorm(0, 0.1, size=N)
beta = [0.1, 0.3, 0.5]

y = np.dot(X, beta) + eps

In [233]:
#! ipython id=81c61bc21b6c409aa2aaa99a3f575bfb
X[:5]
y[:5]

array([-0.59952668, -0.58845445,  0.18563386, -0.00747657, -0.01537445])

In [234]:
#! ipython id=8ae5538884bb4d05bff507be6a9c3d53
X_model = sm.add_constant(X)
X_model[:5]

array([[ 1.        , -0.90050602, -0.18942958, -1.0278702 ],
       [ 1.        ,  0.79925205, -1.54598388, -0.32739708],
       [ 1.        , -0.55065483, -0.12025429,  0.32935899],
       [ 1.        , -0.16391555,  0.82403985,  0.20827485],
       [ 1.        , -0.04765129, -0.21314698, -0.04824364]])

In [236]:
#! ipython id=5ee479f40b0d49f1b8725a3ff80d5794
model = sm.OLS(y, X)
model

In [237]:
#! ipython id=dab4d3edbde744b0ae331d4fac14a62b
results = model.fit()
results.params

array([0.06681503, 0.26803235, 0.45052319])

In [238]:
#! ipython id=f6cacdd9108340b7b7888be9cccb8c66
print(results.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.469
Model:                            OLS   Adj. R-squared (uncentered):              0.452
Method:                 Least Squares   F-statistic:                              28.51
Date:                Fri, 02 Sep 2022   Prob (F-statistic):                    2.66e-13
Time:                        11:58:31   Log-Likelihood:                         -25.611
No. Observations:                 100   AIC:                                      57.22
Df Residuals:                      97   BIC:                                      65.04
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [239]:
#! ipython id=e7dc7a51f95240d690847760a4bce30e
data = pd.DataFrame(X, columns=['col0', 'col1', 'col2'])
data['y'] = y
data[:5]

col0      col1      col2         y
0 -0.900506 -0.189430 -1.027870 -0.599527
1  0.799252 -1.545984 -0.327397 -0.588454
2 -0.550655 -0.120254  0.329359  0.185634
3 -0.163916  0.824040  0.208275 -0.007477
4 -0.047651 -0.213147 -0.048244 -0.015374

In [243]:
#! ipython id=44341d4bc2984b1f9eefdf0518c00b32
results = smf.ols('y ~ col0 + col1 + col2', data=data).fit()
results.params


Intercept   -0.020799
col0         0.065813
col1         0.268970
col2         0.449419
dtype: float64

In [244]:
results.tvalues

Intercept   -0.652501
col0         1.219768
col1         6.312369
col2         6.567428
dtype: float64

In [242]:
#! ipython id=c1e9fd6361f747fcbdd7054fdea0b3e0
results.predict(data[:5])

0   -0.592959
1   -0.531160
2    0.058636
3    0.283658
4   -0.102947
dtype: float64

In [245]:
#! ipython verbatim id=271bfcc9f59a4d2096cc41fdcf9f7fef
init_x = 4

values = [init_x, init_x]
N = 1000

b0 = 0.8
b1 = -0.4
noise = dnorm(0, 0.1, N)
for i in range(N):
    new_x = values[-1] * b0 + values[-2] * b1 + noise[i]
    values.append(new_x)

In [246]:
#! ipython id=e576aacedffa4dbab3be7517065e0b78
from statsmodels.tsa.ar_model import AutoReg
MAXLAGS = 5
model = AutoReg(values, MAXLAGS)
results = model.fit()

In [247]:
#! ipython id=a43500bc16854e43977c0a4c5fc2a2de
results.params

array([ 0.02346612,  0.8096828 , -0.42865278, -0.03336517,  0.04267874,
       -0.05671529])

In [248]:
#! ipython id=9e54440f129e4624889185d002432371
train = pd.read_csv('datasets/titanic/train.csv')
test = pd.read_csv('datasets/titanic/test.csv')
train.head(4)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [249]:
#! ipython id=ea68d69bba434e0c9665c794accee8d8
train.isna().sum()


PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [250]:
test.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [251]:
#! ipython id=ca1197b7e36e4af8bb0c7087960dca2e
impute_value = train['Age'].median()
train['Age'] = train['Age'].fillna(impute_value)
test['Age'] = test['Age'].fillna(impute_value)

In [253]:
#! ipython id=52d11da1850c463783b6e088f0f662d3
train['IsFemale'] = (train['Sex'] == 'female').astype(int)
test['IsFemale'] = (test['Sex'] == 'female').astype(int)

In [255]:
#! ipython id=450811815c5f40d0af45346441c2e3c2
predictors = ['Pclass', 'IsFemale', 'Age']

X_train = train[predictors].to_numpy()
X_test = test[predictors].to_numpy()
y_train = train['Survived'].to_numpy()
X_train[:5]


array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [256]:
y_train[:5]

array([0, 1, 1, 1, 0], dtype=int64)

In [263]:
!pip3 install sklearn

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 7.4/7.4 MB 1.8 MB/s eta 0:00:00
     ------------------------------------ 307.0/307.0 kB 527.0 kB/s eta 0:00:00
Using legacy 'setup.py install' for sklearn, since package 'wheel' is not installed.
  Running setup.py install for sklearn: started
  Running setup.py install for sklearn: finished with status 'done'



[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [264]:
#! ipython id=8a75f2aaf25b449b9347d5a71a1fa643

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [265]:
#! ipython id=d15acba4d6674ea58746c2258c28bf44
model.fit(X_train, y_train)

LogisticRegression()

In [266]:
#! ipython id=27541b6b54c54a37b01dcb07921952b2
y_predict = model.predict(X_test)
y_predict[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

In [270]:
#! ipython id=8a33d87df19f49ec9e62bcb26d88b3b7
from sklearn.linear_model import LogisticRegressionCV
model_cv = LogisticRegressionCV(Cs=10)
model_cv.fit(X_train, y_train)

LogisticRegressionCV()

In [268]:
#! ipython id=36245c79ec40498f8bcb84258c1020cd
from sklearn.model_selection import cross_val_score
model = LogisticRegression(C=10)
scores = cross_val_score(model, X_train, y_train, cv=4)
scores

array([0.77578475, 0.79820628, 0.77578475, 0.78828829])

In [45]:
#! ipython suppress id=ce2a8a40e5074d149cd991bc1062381c
%popd

In [46]:
#! ipython suppress id=de44cca014a54e88a10784f41350688a
pd.options.display.max_rows = PREVIOUS_MAX_ROWS